### PR TITLE
Fix issue with ? in class names

### LINKED ISSUE #290: Columns containing question marks are rendered strangely
In my user model I have:

```elixir
field :admin?, :boolean
```

This results in:
image

### PR DESCRIPTION
**Pull request by gwincr11**
Motivation:
  - Fix issue fixes #290

Changes:
  - classes with ?'s are breaking the html so I am removing them.

### CODE REVIEW

File: test/support/schema.exs [hunk 1]
```diff
@@ -131,6 +131,7 @@ defmodule TestExAdmin.Simple do
   schema "simples" do
     field :name, :string
     field :description, :string
+    field :exists, :boolean, virtual: true
```
Comment (hut8) [inline test/support/schema.exs]: I'm not sure if this matters, but for the sake of completeness, in my use case, this would be `:exists?`

**Comment by gwincr11** [comment]
@hut8  thanks for the heads up. It should not affect anything. The schema is actually not being used in that part of the code, because you set the field with a dsl function call.

**Comment by smpallen99** [comment]
Thanks @gwincr11 !!
